### PR TITLE
Footer Made Responsive

### LINKED ISSUE #95: 🐛 Bug Report: Footer responsive issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

breakpoint = 1350px

after 1350px screen size the diagonal lines joining the join button at the center of footer is not connecting at join buttons respective edges.

image

### Expected Behavior

Diagonal lines should connect the respective edges of join button.

image

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by ojasaklechayt**
**Notes for Reviewers**

This PR fixes #95

Describe the changes you've made:
Made the footer responsive

Screenshots for the change:
image

### CODE REVIEW

**Comment by ArunPatel02** [comment]
@ojasaklechayt can you look into the merge conflict

**Comment by ojasaklechayt** [comment]
> @ojasaklechayt can you look into the merge conflict

Okay I will check

**Comment by ArunPatel02** [comment]
@ojasaklechayt  you have done a force pushed. but you have closed the pr so we are not able to merge your code so these steps you can follow 
1, resolve all  the merge conflict while looking into the file who is having conflicts. 
2. commit and push your code into your local fork repo.
3. create pr to merge your code to main gdscitm branch.

**Comment by ojasaklechayt** [comment]
> @ojasaklechayt you have done a force pushed. but you have closed the pr so we are not able to merge your code so these steps you can follow 1, resolve all the merge conflict while looking into the file who is having conflicts. 2. commit and push your code into your local fork repo. 3. create pr to merge your code to main gdscitm branch.

I think the merge conflict is because of the other prs which were merged before mine and we both have done changes in app.js. hence issue. I have created another pr. Can you please check ?

**Pull request closed without merging**
