### PR TITLE
docs: Modified README file by adding maintainers section

### PR DESCRIPTION
**Pull request by mukadas026**
- [x] Create a section in README.md as `maintainers`
- [x] Add Arun Patel's photo and GitHub user id

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
LGTM @mukadas026 👏 can you share a screenshot of how it looks that would be helpful

**Comment by Yashsharma1911** [comment]
This PR fixes #55

**Comment by mukadas026** [comment]
<a href="https://imgbb.com/">Screenshot-2023-03-11-8-18-53-PM</a>

**Comment by mukadas026** [comment]
I hope it's clear enough @Yashsharma1911

**Comment by Yashsharma1911** [comment]
thanks @mukadas026

**Comment by Yashsharma1911** [comment]
@mukadas026 there are some same related issues too where you can help by the way you have done some good work

**Comment by mukadas026** [comment]
Thank you so much @Yashsharma1911 
What are these related issues I can help with?

**Comment by mukadas026** [comment]
Thank you so much @Yashsharma1911 
What are these related issues I can help with?

**Comment by Yashsharma1911** [comment]
would you like to take this one [issue57](https://github.com/GDSCITM/GDSCITM-official-website/issues/57)

**Comment by mukadas026** [comment]
I'll look through the issues to find a suitable one @Yashsharma1911

**Pull request merged**
