### PR TITLE
fix-team48 

### LINKED ISSUE #48: 🐛 Bug Report: Team Section is not Responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

team cards are merging with each other 

### Expected Behavior

It should not merge with each other instead of it, it should be wrap after it will be at mobile view

image

### Steps To Reproduce

_No response_

### Anything else?

nothing else

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by iamsid0908**
**Notes for Reviewers**

This PR fixes #48

Describe the changes you've made:

Screenshots for the change:

Screenshot from 2023-04-08 15-07-43

### CODE REVIEW

**Review by ArunPatel02 — CHANGES_REQUESTED** [review]
your code is changing the original card design 

**current behavior**
image


**Expected behavior**
image

**Review by martinyis — COMMENTED** [review]
There is still wierd behavior for mobile devices
image

**Comment by sumitshinde-84** [comment]
> There is still wierd behavior for mobile devices image

to resolve this you can show card by making single row slider for mobile version

**Comment by ArunPatel02** [comment]
@iamsid0908 can you look into the requested changes .

**Comment by iamsid0908** [comment]
Screenshot from 2023-04-09 18-18-14

@sumitshinde-84 what do you think?

**Comment by iamsid0908** [comment]
Screenshot from 2023-04-09 18-19-51

**Comment by sumitshinde-84** [comment]
> Screenshot from 2023-04-09 18-18-14
> 
> @sumitshinde-84 what do you think?
Try to convert it in one row slider for mobile version 
sliding card  post
Like this

**Comment by ArunPatel02** [comment]
> Screenshot from 2023-04-09 18-19-51
> 

You can apply different numbers column for different breakpoint

For example for big screens you can have 4 columns

for small device you can have 2 columns

For screen size less that 350px you can have 1 column

**Comment by kamalchakma1** [comment]
Its change the original card design.

**Comment by iamsid0908** [comment]
okay

**Comment by iamsid0908** [comment]
[Screencast from 09-04-23 10:27:20 PM IST.webm](https://user-images.githubusercontent.com/86674873/230786012-fe79dd55-a368-4b0b-8547-f0c3a596472e.webm)
@sumitshinde-84 @ArunPatel02

**Comment by ArunPatel02** [comment]
> [Screencast from 09-04-23 10:27:20 PM IST.webm](https://user-images.githubusercontent.com/86674873/230786012-fe79dd55-a368-4b0b-8547-f0c3a596472e.webm)
> @sumitshinde-84 @ArunPatel02 

Looking good to me @iamsid0908. Can we have others suggestions as well. What do you all thinks @kamalchakma1 @anshitmishra @martinyis

**Review by ArunPatel02 — CHANGES_REQUESTED** [review]
card box shadow changed 

**Current Behavior**
image

**Expected Behavior**
image

**Comment by anshitmishra** [comment]
@iamsid0908 I have one suggestion when the user hovers over the card scale card size and makes the box shadow a little bit dark. it will look good and attractive to users. you view on this @ArunPatel02 @kamalchakma1 @martinyis  @Yashsharma1911

**Comment by ArunPatel02** [comment]
> @iamsid0908 I have one suggestion when the user hovers over the card scale card size and makes the box shadow a little bit dark. it will look good and attractive to users. your view on this @ArunPatel02 @kamalchakma1 @martinyis @Yashsharma1911

sounds good @anshitmishra thank you for your suggestion. can you please create new issue for this hover effect ?

**Comment by anshitmishra** [comment]
> > @iamsid0908 I have one suggestion when the user hovers over the card scale card size and makes the box shadow a little bit dark. it will look good and attractive to users. your view on this @ArunPatel02 @kamalchakma1 @martinyis @Yashsharma1911
> 
> sounds good @anshitmishra thank you for your suggestion. can you please create new issue for this hover effect ?

sure 😊

**Comment by kamalchakma1** [comment]
It's actually good idea.

**Comment by iamsid0908** [comment]
> card box shadow changed
> 
> **Current Behavior** image
> 
> **Expected Behavior** image

give the preset of this @ArunPatel02

**Comment by iamsid0908** [comment]
> card box shadow changed
> 
> **Current Behavior** image
> 
> **Expected Behavior** image

give the shadow preset or property of this.

**Pull request closed without merging**
