### PR TITLE
Add files via upload

### LINKED ISSUE #95: 🐛 Bug Report: Footer responsive issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

breakpoint = 1350px

after 1350px screen size the diagonal lines joining the join button at the center of footer is not connecting at join buttons respective edges.

image

### Expected Behavior

Diagonal lines should connect the respective edges of join button.

image

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by ojasaklechayt**
**Notes for Reviewers**

This PR fixes #95 

Describe the changes you've made:
Made footer responsive

Screenshots for the change:
image

image

### CODE REVIEW

**Comment by ojasaklechayt** [comment]
@ArunPatel02 I think this might be the final pr I will be making.

**Comment by ojasaklechayt** [comment]
@ArunPatel02 Is this correct ?

**Review by martinyis — COMMENTED** [review]
I didn't really notice any changes. A footer was already responsive and everything worked well. The file name is also changed to .jsx format which is not good when the whole project has .js format

**Comment by ojasaklechayt** [comment]
> I didn't really notice any changes. A footer was already responsive and everything worked well. The file name is also changed to .jsx format which is not good when the whole project has .js format

there were some error in footer. It wasn't fully responsive. jsx was the by default form which I got in my pc

**Review by kamalchakma1 — COMMENTED** [review]
Everything seems good. If file extension is the problem you think then try to change it to .js and then check it.

**Comment by Yashsharma1911** [comment]
some good reviews are here @ojasaklechayt can we merge this pr @martinyis @kamalchakma1

**Comment by kamalchakma1** [comment]
Hi @ojasaklechayt I checked and its showing same(breaking). Can you apply CSS for screens greater than **1355**. Till 1355 its working fine but when we increase screen size greater than 1355 its start breaking.

**Comment by Yashsharma1911** [comment]
@ojasaklechayt thank for changes I think there is still need some work after 1300 pixel till it looks good to me let's get this PR merge as we are in sprint to make this website fast please create new issue for that and you can work on it or we have some more issue that you can take them down with your skills 😉

**Comment by Yashsharma1911** [comment]
wow @ojasaklechayt this was your first contribution to GDSC ITM, welcome to GDSC ITM @ojasaklechayt

**Pull request merged**
