### PR TITLE
added hamburger menu with working 

### PR DESCRIPTION
**Pull request by anshitmishra**
**Notes for Reviewers**

This PR fixes #
#12 
#104 

Describe the changes you've made:
added hamburger menu with working and responsive
also, change in event css added margin in the data

Screenshots for the change:
Screenshot (30)

Screenshot (32)

### CODE REVIEW

**Comment by anshitmishra** [comment]
@Yashsharma1911 plz check this pr asap

**Comment by Yashsharma1911** [comment]
yes changes are required @anshitmishra but if you are in running out of time we can merge this PR later then you can create new subsequent pr 

before merge make one change please remove you photo and name from that if we will merge with that static data users will feel like they are logged in with your id

**Comment by Yashsharma1911** [comment]
or let's just remove logout and user profile from menu until we introduce firebase please make that change and keep all items except profile section and logout button

**Comment by anshitmishra** [comment]
Screenshot_20230407_142852_Chrome


@Yashsharma1911 any other changes

**Comment by anshitmishra** [comment]
@Yashsharma1911 any other changes are required in this

**Comment by anshitmishra** [comment]
@Yashsharma1911 any other changes need to do if not plz merge this pr

**Review by ArunPatel02 — APPROVED** [review]

**Comment by anshitmishra** [comment]
@ArunPatel02  bhiya plz merge this pr so that i can work on new prs

**Comment by ArunPatel02** [comment]
> @ArunPatel02  bhiya plz merge this pr so that i can work on new prs
> 

Ok @anshitmishra

**Pull request merged**
