### PR TITLE
issue first added menu for phone size add new logo added style file r…

### PR DESCRIPTION
**Pull request by anshitmishra**
issue first added menu for phone size add new logo added style file removed the old logo

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Hey @anshitmishra please review the design file for changes by [Clicking here](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=gsZ2VE6Coa8bv50Z-0)

## 🚀 This is a screenshot of the expected behavior
 
Screenshot 2022-12-24 at 11 37 50 PM

## 🐛  This is the current behavior
Screenshot 2022-12-24 at 11 35 02 PM

**Comment by Yashsharma1911** [comment]
@anshitmishra are you still working on this PR

**Comment by Yashsharma1911** [comment]
Hey, @anshitmishra you have done great work just let me know, are you still working on this PR if yes then remove the merge conflict, and let's get this done...

**Comment by anshitmishra** [comment]
I will raise new pr soon...

**Pull request closed without merging**
