### PR TITLE
fix: #56 Change title from 'React App' to 'GDSC ITM'

### LINKED ISSUE #56: 🐛 Bug Report: Change title from 'React App' to 'GDSC ITM'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The GDSC ITM website has 'React App' as the title (see attached screenshot), which makes the website looks unprofessional and degrades the authenticity.
opensrc1

### Expected Behavior

It should be changed to a better title like 'GDSC ITM'. 

### Steps To Reproduce

_No response_

### Anything else?

Please allow me to fix that.

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by PalakJain9**
I've changed the website's title from the default 'React App' to 'GDSC ITM'.
Kindly review my PR.

### CODE REVIEW

**Review by ArunPatel02 — APPROVED** [review]

**Review by Yashsharma1911 — CHANGES_REQUESTED** [review]
LGTM 👏 as you are there can you do one more thing, we also need to replace that react icon with GDSC logo that would be helpful

Screenshot 2023-03-12 at 2 48 32 PM

**Comment by PalakJain9** [comment]
Sure @Yashsharma1911 , working on it

**Comment by Yashsharma1911** [comment]
issue #62 and #63 have the same doc-related issues which you can take them down 😎

**Comment by PalakJain9** [comment]
Hey, I haven't dismissed any review nor have I chosen any other option, yet I see the message of dismissing ArunPatel02's review. What could be the possible reason?

**Review by ArunPatel02 — APPROVED** [review]
Great work @PalakJain9 you have done a wonderful job👍👍

**Review by ArunPatel02 — APPROVED** [review]

**Comment by PalakJain9** [comment]
Thanks @ArunPatel02 @Yashsharma1911  for your support and cooperation.

**Pull request merged**
