### PR TITLE
changes according to figma design in about section

### PR DESCRIPTION
**Pull request by anshitmishra**
**Notes for Reviewers**

This PR fixes #

#132 
Describe the changes you've made:
made changes in about section according to figma design

Screenshots for the change:
Screenshot (22)

### CODE REVIEW

**Review by ArunPatel02 — CHANGES_REQUESTED** [review]
thank you @anshitmishra  for you contribution . would you please make the font weight : 400 and font-size : 17 or 18px for the marked section and would you please increase the top margin for what is gdsc typo .

image

**Comment by Yashsharma1911** [comment]
FYI @anshitmishra and @ArunPatel02 if changes are small and you are reviewing PR try if you can directly make changes in that PR this will help us to move fast

**Comment by anshitmishra** [comment]
Screenshot (26)
Screenshot (25)

@Yashsharma1911 @ArunPatel02  @sudhanshutech  added new gallery section 

#140 
@ArunPatel02  also added font size and font weight  

but i believe that i can give some input in figma design so please provide figma edit access so i can create a copy of design so i can edit

**Review by ArunPatel02 — APPROVED** [review]

**Comment by Yashsharma1911** [comment]
ohh that looks great thanks anshit just need more photos there would you mind creating new issue for that and provide some photos there

**Review by Yashsharma1911 — APPROVED** [review]

**Comment by Yashsharma1911** [comment]
some darn fine work here by @anshitmishra 👏

**Comment by anshitmishra** [comment]
> ohh that looks great thanks anshit just need more photos there would you mind creating new issue for that and provide some photos there

sure i will create issue for that

**Pull request merged**
