### PR TITLE
Fix contributors count

### LINKED ISSUE #62: 📚 Documentation: all contributors count is not correct
### 💬 Description

All contributers count is wrong as we are having 11 contributers but it is only showing 2.

Screenshot_2023-03-12-15-05-44-69_40deb401b9ffe8e1df2f1cc5ba480b12

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

### PR DESCRIPTION
**Pull request by Soumya-Kushwaha**
Fixes #62

### CODE REVIEW

**Comment by ArunPatel02** [comment]
> Fixes #62 

@Soumya-Kushwaha you recent pr removing all contributers badge

**Comment by Soumya-Kushwaha** [comment]
@ArunPatel02 The contributors badge is still available!

image

**Comment by ArunPatel02** [comment]
> @ArunPatel02 The contributors badge is still available!
> 
> image
> 

@Soumya-Kushwaha in that case you can remove all contributers badge

**Comment by Soumya-Kushwaha** [comment]
> > @ArunPatel02 The contributors badge is still available!
> > image
> 
> @Soumya-Kushwaha in that case you can remove all contributers badge

This PR does the same!

**Comment by ArunPatel02** [comment]
> > > @ArunPatel02 The contributors badge is still available!
> > > image
> > 
> > 
> > @Soumya-Kushwaha in that case you can remove all contributers badge
> 
> @ArunPatel02 This PR does the same!

Great work @Soumya-Kushwaha  and thank you for pointing out the contributors badge problem.

**Comment by Soumya-Kushwaha** [comment]
@ArunPatel02 Thank you!

**Comment by Yashsharma1911** [comment]
Good work by @Soumya-Kushwaha would you like to share about your main tech stack let's get you ramped up with more impactful things

**Comment by Soumya-Kushwaha** [comment]
Hey @Yashsharma1911 sounds great!
I am currently working on Machine Learning and Artificial Intelligence and have decent experience in Python and Data Science

**Pull request merged**
