### PR TITLE
Header text font size in small screen fixed

### PR DESCRIPTION
**Pull request by kamalchakma1**
Hi, Please check. Thank you

### CODE REVIEW

**Review by sudhanshutech — APPROVED** [review]
Good work

**Review by ArunPatel02 — APPROVED** [review]

**Comment by ArunPatel02** [comment]
> Hi, Please check. Thank you

Thank you @kamalchakma1 for your valuable contribution.

**Comment by ArunPatel02** [comment]
> > Hi, Please check. Thank you
> 
> Thank you @kamalchakma1 for your valuable contribution.

There are similar issues would you like to contribution in those issues?

**Comment by kamalchakma1** [comment]
@sudhanshutech thanks

**Comment by kamalchakma1** [comment]
@ArunPatel02 sure

**Comment by ArunPatel02** [comment]
> @ArunPatel02 sure I would love to fix similar issue

great @kamalchakma1  you can look issue #18 and #19 they have some sections needs to be created.

**Comment by kamalchakma1** [comment]
@ArunPatel02 sure assign me issue #19

**Pull request merged**
