### PR TITLE
its fixed input works now

### LINKED ISSUE #111: 🐛 Bug Report: home section input textbox issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not able to email my email in the given email text field 
image

### Expected Behavior

User can able to enter email in the email field

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by bilalakhter**
**Notes for Reviewers**

This PR fixes #111 input field now works

Describe the changes you've made:
changed the position of input and button next to it needed some margin left so that input and button both works

Screenshots for the change:

### CODE REVIEW

**Comment by bilalakhter** [comment]
gimme a try

**Comment by bilalakhter** [comment]
should the button stays in some style as it is like over the input field?

**Comment by Yashsharma1911** [comment]
we need that if any user clicks on any part of the input field they can type and yes button don't need any changes as it is part of UI design which you can find here [figma](https://www.figma.com/file/PZcP2X9CdePgwlQqy8Ym5Y/GDSC-(Copy)?node-id=0%3A1&t=du9dGcaWFeJu1BM6-1)

**Comment by bilalakhter** [comment]
check now

**Comment by Yashsharma1911** [comment]
thanks for fixing it asap @bilalakhter

**Review by Yashsharma1911 — APPROVED** [review]

**Pull request merged**
