### PR TITLE
fix: responsive alignment fixed

### LINKED ISSUE #90: 🐛 Bug Report: Text, input field is not  Responsive  in small screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text section, input field and button below Nav bar is not in proper order. Please check screenshot

responsive issue

### Expected Behavior

Align text section, input field and button at center.
 
Expected result

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by Mr-G-D**
**Notes for Reviewers**

This PR fixes #90 
- Alignment issue for small screens

Describe the changes you've made:
- made css changes to fix the responsive alignment in the home screen

Screenshots for the change:
final

### CODE REVIEW

**Review by ArunPatel02 — CHANGES_REQUESTED** [review]
thank a lot @Mr-G-D  for you wonder full contribution 
would you please decrease the gap between (come join us and beginning of infinity) 
image

**Review by ArunPatel02 — APPROVED** [review]

**Comment by ArunPatel02** [comment]
Thank a lot @Mr-G-D you have done a wonderful contribution. 
Would you like to look into some similar responsive issues?

**Comment by Yashsharma1911** [comment]
oh wow @Mr-G-D we were in need of this changes as it was our hero section of website thanks

**Comment by Mr-G-D** [comment]
@ArunPatel02 
Sure, I can look into it

**Comment by Mr-G-D** [comment]
@ArunPatel02 @Yashsharma1911 
Hello friends, just let me know if there is any other task that needs to get done

**Comment by ArunPatel02** [comment]
> @ArunPatel02 @Yashsharma1911 
> Hello friends, just let me know if there is any other task that needs to be done 

Hello @Mr-G-D we appreciate you contribution. If you like you can take issue #18 .

**Pull request merged**
