### PR TITLE
Added link tags to each nav-item on the navbar in the Header component

### LINKED ISSUE #91: 🐛 Bug Report: Redirect to section of page on clicking navbar menus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently in navbar we have different menu items like home, about , event and team but on clicking them there is no effect.
image

### Expected Behavior

Redirect on clicking on those menu items to respective section of page like event->event section, about->about section.

### Steps To Reproduce

Use routes to redirect to particular section

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by mukadas026**
**Notes for Reviewers**
On ciick on each nav item, it redirects you to the specific section of the page

This PR fixes #91 

**Describe the changes you've made:**
Wrapped each of the nav-bar items in the Header component with a link component.

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
@bilalakhter would you like to review here

**Review by bilalakhter — APPROVED** [review]
gracias @mukadas026

**Review by bilalakhter — APPROVED** [review]

**Comment by ArunPatel02** [comment]
@Yashsharma1911 can we merge this code?

**Comment by Yashsharma1911** [comment]
Yes please and thankyou @mukadas026 and @bilalakhter

**Pull request merged**
