### PR TITLE
Fixed merge conflict

### PR DESCRIPTION
**Pull request by martinyis**
Fix issue #77

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
@martinyis please check deploy fail

**Comment by Yashsharma1911** [comment]
you don't need to create new PR again that deploy fail is coming in `/src/Components/Header.js` at line 15 please fix that then we are good to go

**Comment by martinyis** [comment]
@Yashsharma1911 I just fixed that problem with merge conflict and I also fixed some font-family issues in the About section.
Sorry for a late fix!

**Review by ArunPatel02 — APPROVED** [review]

**Comment by Yashsharma1911** [comment]
thanks @martinyis, need to say you have done some darn work with the theme we were in need of that we also have some related issue with which you can help let me know if need any help to find one 😉

**Pull request merged**
