### PR TITLE
Hemanth paila display all events

### LINKED ISSUE #98: 🐛 Bug Report: Display all events when clicked on 'All' tab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the events section, when you click on the `All` tab, data of the `Past` tab has been shown (i.e. events held in the past are shown). Take a look at below screenshot :

-
opensrc1

### Expected Behavior

The desired behavior is to show all the events when `All` tab is chosen.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by HemanthPaila**
**Notes for Reviewers**

This PR fixes #98 

Describe the changes you've made:
I made changes to Event.js and Event.css files.

Screenshots for the change:
Screenshot (16)

### CODE REVIEW

**Comment by ArunPatel02** [comment]
@HemanthPaila your code is having merge conflicts can you please resolve the conflicts

**Comment by HemanthPaila** [comment]
ok sorry I forget to check it. My bad.

**Comment by Yashsharma1911** [comment]
@ArslanYM would you like to review here

**Comment by ArslanYM** [comment]
> @ArslanYM would you like to review here

Sure.

**Comment by ArslanYM** [comment]
@HemanthPaila When you're solving an issue , try to fix the stated issue only rather than making changes in other sections as well.
Here it looks like youve changed the CSS of the card 
The card looked something like this before:
before


After your changes:
after

Notice there was some padding present between the title of the card and content.

**Comment by HemanthPaila** [comment]
Haa @ArslanYM. I will take care of it I didn't check.
- anyway I will make another PR.

**Comment by anshitmishra** [comment]
@Yashsharma1911 i have resolve merge conflict so plz review this

**Review by anshitmishra — COMMENTED** [review]
done some changes in event.js file and still i have one qns i did't understand from where pastData we are getting so check line 37 in event.js i made temp pasrData but need to change @Yashsharma1911

**Comment by HemanthPaila** [comment]
Hello @anshitmishra .

pastData:
const[pastData,setPastData]=useState([
        {id:"1",date:"01",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs"
        ,topImage:"/images/bg1.png",color:"#ffd34e"},
        {id:"2",date:"02",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs"
        ,topImage:"/images/bg2.png",color:"#f27770"}
        ,{id:"3",date:"03",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs"
        ,topImage:"/images/bg3.png",color:"#3eaff4"},
        {id:"4",date:"04",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs"
        ,topImage:"/images/bg4.png",color:"#6ebb71"},
        {id:"5",date:"06",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs"
        ,topImage:"/images/bg2.png",color:"#f47169"},
        {id:"6",date:"06",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs"
        ,topImage:"/images/bg1.png",color:"#ffd34e"}
    ])

- above was the pastData.
- while resolving the conflicts, I made mistakes.

**Comment by anshitmishra** [comment]
> Hello @anshitmishra .
> 
> pastData: const[pastData,setPastData]=useState([ {id:"1",date:"01",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs" ,topImage:"/images/bg1.png",color:"#ffd34e"}, {id:"2",date:"02",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs" ,topImage:"/images/bg2.png",color:"#f27770"} ,{id:"3",date:"03",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs" ,topImage:"/images/bg3.png",color:"#3eaff4"}, {id:"4",date:"04",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs" ,topImage:"/images/bg4.png",color:"#6ebb71"}, {id:"5",date:"06",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs" ,topImage:"/images/bg2.png",color:"#f47169"}, {id:"6",date:"06",month:"sep 22",topic:"Orientation Session",text:"We are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students ClubsWe are having a live session where we will introduce you to Google Developer Students Clubs" ,topImage:"/images/bg1.png",color:"#ffd34e"} ])
> 
> * above was the pastData.
> * while resolving the conflicts, I made mistakes.

ok @HemanthPaila i will add this data in this pr that will be very helpful

**Comment by HemanthPaila** [comment]
Could stay online for a while. We both can resolve this.
- need to add some changes.

**Review by anshitmishra — APPROVED** [review]
@HemanthPaila thanks for your contribution

**Comment by anshitmishra** [comment]
> Could stay online for a while. We both can resolve this.
> 
> * need to add some changes.

yaa but i believe issue is resolved @HemanthPaila

**Comment by HemanthPaila** [comment]
@anshitmishra I am looking for a merge.

**Review by anshitmishra — APPROVED** [review]

**Comment by Yashsharma1911** [comment]
nice some peer work here Thanks @HemanthPaila and @anshitmishra can we merge this PR @anshitmishra

**Comment by anshitmishra** [comment]
> nice some peer work here Thanks @HemanthPaila and @anshitmishra can we merge this PR @anshitmishra

yes every thing is fine now @Yashsharma1911

**Comment by HemanthPaila** [comment]
No, I think @ArslanYM needs some changes to it. Could you please check in the conversation.
But thanks @anshitmishra.

**Comment by ArslanYM** [comment]
@Yashsharma1911 LGTM

**Comment by anshitmishra** [comment]
> No, I think @ArslanYM needs some changes to it. Could you please check in the conversation. But thanks @anshitmishra.

i believe @ArslanYM changes are done because the padding part is done it looks great to me @Yashsharma1911 check this

**Comment by HemanthPaila** [comment]
Ok, @anshitmishra.

**Comment by anshitmishra** [comment]
@Yashsharma1911 we can merge this pr every thing is fine

**Review by anshitmishra — APPROVED** [review]

**Pull request merged**
