### PR TITLE
Fix: Email gets hide when user types their email

### PR DESCRIPTION
**Pull request by NJ-2020**
Close: #6 

## What changes I made: 
I Fixed the home input email hidden part when the user has to type a long email address.

## File changed
1: ```Home.js```

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Hey @NJ-2020 rather than overflow and hide the text if you can increase the width of the input field that will be good for UI design purposes too

**Comment by NJ-2020** [comment]
Okay

**Comment by NJ-2020** [comment]
> Hey @NJ-2020 rather than overflow and hide the text if you can increase the width of the input field that will be good for UI design purposes too

Done!

**Comment by ArunPatel02** [comment]
#6 
#11 
## 👍 Expected behavior
The email input by the user should be seen properly on small-screen devices too.

## 👎 Actual Behavior
image 

🐛 On the small screen, the email is not showing properly as there is a lot of blank space between the red pointer and button, where the user is not able to type.

**Review by ArunPatel02 — COMMENTED** [review]
#6 
#11 
## 👍 Expected behavior
The email input by the user should be seen properly on small-screen devices too.

## 👎 Actual Behavior
image 

🐛 On the small screen, the email is not showing properly as there is a lot of blank space between the red pointer and button, where the user is not able to type.

**Comment by NJ-2020** [comment]
> The email input by the user should be seen properly on small-screen devices too.

Done, I've fixed it!

**Pull request merged**
