### PR TITLE
data store added for fetching team members

### LINKED ISSUE #144: 🚀 Feature: fetch the teams details from the repo name as gdsc-data
### 📜 Feature Description

fetch the team data from the repo gdsc-data from data.json

### 🎤 Pitch

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Yes, I have read Code of Conduct.

### PR DESCRIPTION
**Pull request by ArunPatel02**
**Notes for Reviewers**

This PR fixes #144 

Describe the changes you've made:
create a repo name as gdsc-datastore from where I am fetching the data for team members

Screenshots for the change:
image

### CODE REVIEW

**Review by sudhanshutech — COMMENTED** [review]
@ArunPatel02 does adding data to datastore repo will automatically reflect here the changes

**Comment by ArunPatel02** [comment]
> @ArunPatel02 does adding data to datastore repo will automatically reflect here the changes

Yes @sudhanshutech

**Comment by ArunPatel02** [comment]
We also need to add social media links of each member https://github.com/GDSCITM/GDSC-dataStore/issues/2

**Comment by Yashsharma1911** [comment]
@GDSCITM/techteam please be aware of this change

**Comment by Yashsharma1911** [comment]
are we ready to merge this PR @ArunPatel02

**Comment by anshitmishra** [comment]
> are we ready to merge this PR @ArunPatel02

just one more suggestion if we are working on this part. so we can go with a new design @Yashsharma1911 @ArunPatel02

**Comment by ArunPatel02** [comment]
> are we ready to merge this PR @ArunPatel02 

Yes we are

**Pull request merged**
