### PR TITLE
Update Home.js

### PR DESCRIPTION
**Pull request by errorline99**
I redesigned the home container as you asked. tell me if i did something wrong so i will fix it

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
Hey @ArunPatel02 check and merge this pull request

**Comment by iamsid0908** [comment]
@errorline99  write your issue number...

**Comment by errorline99** [comment]
issue # 7

**Comment by Yashsharma1911** [comment]
No responses on this PR that' why closing this PR

**Pull request closed without merging**
