### PR TITLE
add gallery fetch images function

### PR DESCRIPTION
**Pull request by sumitshinde-84**
**Notes for Reviewers**

This PR fixes #

Describe the changes you've made:

Screenshots for the change:

### CODE REVIEW

**Comment by sumitshinde-84** [comment]
I have made changes to the Gallery component to fetch images asynchronously instead of using static images. The fetched images are now displayed in the gallery. I have thoroughly reviewed and tested the changes locally.

Please review and let me know if there are any further suggestions, feedback, or if anything seems to be incorrect or needs improvement.

**Comment by ArunPatel02** [comment]
> I have made changes to the Gallery component to fetch images asynchronously instead of using static images. The fetched images are now displayed in the gallery. I have thoroughly reviewed and tested the changes locally.
> 
> Please review and let me know if there are any further suggestions, feedback, or if anything seems to be incorrect or needs improvement.

thanks a lot @sumitshinde-84 for your wonderful contribution. we rally need this feature . you did a wonderful job.

**Comment by sumitshinde-84** [comment]
@ArunPatel02 Please let me know if there are any other tasks or issues I can help with.

**Comment by ArunPatel02** [comment]
@sumitshinde-84  can you look at this i am not seeing any images in gallery section 
image

**Comment by sumitshinde-84** [comment]
Let me make some changes

**Comment by sumitshinde-84** [comment]
Now its working fine see i have made some changes

**Review by ArunPatel02 — APPROVED** [review]

**Review by anshitmishra — APPROVED** [review]

**Comment by kamalchakma1** [comment]
First when I check I saw images but after that  I am not able to see images now.

**Comment by sumitshinde-84** [comment]
> First when I check I saw images but after that I am not able to see images now.

Sorry but I just have tested  its working fine

**Review by kamalchakma1 — APPROVED** [review]

**Comment by ArunPatel02** [comment]
Thank you @kamalchakma1 @anshitmishra  for you review. Thank you @sumitshinde-84 for you wonderful contribution.

**Comment by sumitshinde-84** [comment]
> Congrats on merging your first pull request! tadatadatada cat meme
Thanks 🙂

**Pull request merged**
