### PR TITLE
Bug fix: Added hamburger menu items and button for mobile view

### LINKED ISSUE #104: 🐛 Bug Report: Hamburger Nav not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hamburger nav bar not working

### Expected Behavior

It should display the about , teams , teams etc when clicked on small screen devices buts its not

image

checkout this design to inspire and create a component https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1

### Steps To Reproduce

_No response_

### Anything else?

fix

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by Sunny-25**
**Notes for Reviewers**

This PR fixes #104

Describe the changes you've made:
Added hamburger menu items and button for mobile view .

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
@Sunny-25 does this hamburger menu works? if yes it will be helpful if not can you make it work?

**Comment by kamalchakma1** [comment]
Hi @Sunny-25 If it's working in your end can you please share screenshot,it will be very helpful.

**Comment by sudhanshutech** [comment]
anu updates here @Sunny-25 ?

**Comment by Yashsharma1911** [comment]
@anshitmishra do we already solved this in your PR ? 🤔

**Comment by anshitmishra** [comment]
> @anshitmishra do we already solved this in your PR ? 🤔

no, I have created something for that but it is not suitable for Figma design so I need to recreate this hamburger menu option part @Yashsharma1911

**Comment by Yashsharma1911** [comment]
@anshitmishra should we merge this PR?

**Comment by Yashsharma1911** [comment]
@Sunny-25 this issue get's old have you find some new issue to work on do you need any help

**Comment by anshitmishra** [comment]
> @anshitmishra should we merge this PR?

no this part is already done so if we merge this then it will create a conflict or change the design @Yashsharma1911

**Pull request closed without merging**
