### PR TITLE
spacing successfully done

### LINKED ISSUE #82: 🐛 Bug Report: Need more spacing in about section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently subheader and body don't have space between them

Screenshot 2023-03-18 at 9 15 36 PM

### Expected Behavior

Screenshot 2023-03-18 at 9 19 35 PM

### Steps To Reproduce

use relative units of css

### Anything else?

_No response_

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### PR DESCRIPTION
**Pull request by nitin1chandani**
This PR fixes #82
I have just changed the css in which I have changed the padding only .

### CODE REVIEW

**Comment by Yashsharma1911** [comment]
@mukadas026 will you review this PR

**Comment by mukadas026** [comment]
Yes @Yashsharma1911 , I would love to

**Comment by mukadas026** [comment]
one thing tho, I looked at the site and the heading looks fine
image

spacing seems to be okay on my machine.
Also took a look at the PR......Looks good

**Review by mukadas026 — APPROVED** [review]
Everything looks good. Good job
@nitin1chandani please try to remove the multiple empty lines.

**Comment by ArunPatel02** [comment]
Thank you @nitin1chandani for your valuable contribution

**Comment by ArunPatel02** [comment]
thank you @mukadas026 for your review we really appreciate your efforts.

**Comment by mukadas026** [comment]
I really appreciate you giving the chance @ArunPatel02 and @Yashsharma1911 . Thank you!!!

**Pull request merged**
