### PR TITLE
added github icon

### PR DESCRIPTION
**Pull request by bilalakhter**
**Notes for Reviewers**

This PR fixes #
add github icon team slider cards
Describe the changes you've made:
imported adn added icon to component

Screenshots for the change:

### CODE REVIEW

**Comment by bilalakhter** [comment]
sorry missed that

**Comment by bilalakhter** [comment]
check it now

**Review by mukadas026 — APPROVED** [review]
That's an amazing work done @bilalakhter

**Comment by Yashsharma1911** [comment]
resolved merge conflict

**Pull request merged**
