### PR TITLE
docs: Added Contributors.md

### LINKED ISSUE #58: 📚 Documentation: Create `contibutor.md` file to mention all contributors of GDSC
### 💬 Description

We appreciate the efforts of all contributors that's why we are in need to have a file in which we will be mentioning all contributors

### Reference

for reference, I am mentioning a file over here to take inspiration

- [Contributor.md](https://github.com/firstcontributions/first-contributions/blob/main/Contributors.md)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

### PR DESCRIPTION
**Pull request by Soumya-Kushwaha**
Fixes #58

### CODE REVIEW

**Review by Yashsharma1911 — APPROVED** [review]
Thanks @Soumya-Kushwaha LGTM 👏

**Comment by Yashsharma1911** [comment]
nice work @Soumya-Kushwaha we have some same related issues open where you may help let me know if you need any help finding them

**Comment by Soumya-Kushwaha** [comment]
@Yashsharma1911 I would definitely like to work on them. Please let me know about the issues.

**Comment by Yashsharma1911** [comment]
@Soumya-Kushwaha issues https://github.com/GDSCITM/GDSCITM-official-website/issues/62 and https://github.com/GDSCITM/GDSCITM-official-website/issues/63 have the same doc-related issues which you might like to take them down 😎

**Comment by Soumya-Kushwaha** [comment]
Thank you. I'll look into them.

**Pull request merged**
