### PR TITLE
Footer Made Responsive

### LINKED ISSUE #95: 🐛 Bug Report: Footer responsive issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

breakpoint = 1350px

after 1350px screen size the diagonal lines joining the join button at the center of footer is not connecting at join buttons respective edges.

image

### Expected Behavior

Diagonal lines should connect the respective edges of join button.

image

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by ojasaklechayt**
**Notes for Reviewers**

This PR fixes #95 

Describe the changes you've made:

Screenshots for the change:
image

### CODE REVIEW

**Review by kamalchakma1 — COMMENTED** [review]
Hi @ojasaklechayt it will be very helpful if you  can share screenshot of breakpoint = 1350px or desktop view.

**Comment by ojasaklechayt** [comment]
> Hi @ojasaklechayt it will be very helpful if you can share screenshot of breakpoint = 1350px or desktop view.

It would be like this
image

**Review by martinyis — COMMENTED** [review]
As I looked on the website the expected behavior of joining lines already was on the website I didn't really get what is the point of this issue. There are 20 files changed in one commit so I am not sure I am able to take a review for all of those files!

**Comment by ArunPatel02** [comment]
As issue suggested that when screen size exceeds 1350px limit the lines joined the join button edges is separation. So we should connect those diagonal whites lines to the join button edges in footer.

**Comment by ArunPatel02** [comment]
> As I looked on the website the expected behavior of joining lines already was on the website I didn't really get what is the point of this issue. There are 20 files changed in one commit so I am not sure I am able to take a review for all of those files!

As there are 20 files changed so @ojasaklechayt did you pushed those chages through git or upload those changes?

**Comment by kamalchakma1** [comment]
@ArunPatel02 you are right, lines are going away from corner of the Join button.

**Comment by ojasaklechayt** [comment]
> > As I looked on the website the expected behavior of joining lines already was on the website I didn't really get what is the point of this issue. There are 20 files changed in one commit so I am not sure I am able to take a review for all of those files!
> 
> As there are 20 files changed so @ojasaklechayt did you pushed those chages through git or upload those changes?

I think the issue is I made pr last night. Then in morning other prs got merged with some other work which includes work on footer also. I have made changes in footer file only and no changes in other files. So, when I uploaded my work in my fork, the new work got erased. I will try syncing and pushing once again.

**Pull request closed without merging**
