### PR TITLE
Added discord link

### LINKED ISSUE #71: 📚 Documentation: Add community discord link to README file
### 💬 Description

We are a community of 500+ members and we are growing rapidly to help and support contributors let's add a link to discord where they can join and interact with other members

Link of discord - https://discord.com/invite/agGwYPhk9k

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the bug or typo error you wanna add.

### PR DESCRIPTION
**Pull request by Soumya-Kushwaha**
Fixes #71

### CODE REVIEW

**Comment by ArunPatel02** [comment]
@Soumya-Kushwaha can you share the screenshot of the preview

**Comment by Soumya-Kushwaha** [comment]
image
@ArunPatel02

**Comment by ArunPatel02** [comment]
> image @ArunPatel02

@Soumya-Kushwaha  it is possible to make discord shield badge look similar to Gmail , twitter and Instagram.

**Comment by Soumya-Kushwaha** [comment]
@ArunPatel02 I believe this should work
image

But there's something I'd like you to check:
The link says "Unable to accept invite" when trying to join community via the given link

**Comment by ArunPatel02** [comment]
> @ArunPatel02 I believe this should work image
> 
> But there's something I'd like you to check: The link says "Unable to accept invite" when trying to join community via the given link

ok @Soumya-Kushwaha i will check thank for your consideration.

**Comment by ArunPatel02** [comment]
> @ArunPatel02 I believe this should work image
> 
> But there's something I'd like you to check: The link says "Unable to accept invite" when trying to join community via the given link

@Soumya-Kushwaha  it is working super fine. you really did a wonderful job. Thank you for your continuous efforts and contribution.

**Pull request merged**
