### PR TITLE
scroll to about section

### LINKED ISSUE #94: 🐛 Bug Report: scroll to About section on click at 'know more' (on the landing area)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When one clicks at `Know more`, nothing happens. Have a look at this screenshot
  
   
opensrc1

### Expected Behavior

On click at `know more`, it should scroll down to the `about the community` section. Have a look at this screenshot. 

opensrc2

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by masif2002**
This PR fixes #94 

### Changes
* On clicking Know More button, it scrolls to the about section

GIF

### CODE REVIEW

**Review by ArunPatel02 — APPROVED** [review]

**Review by kamalchakma1 — APPROVED** [review]

**Comment by Yashsharma1911** [comment]
Thanks @masif2002 for fixing it

**Comment by Yashsharma1911** [comment]
as you have done some good work here we have some more related issues with which you can help @masif2002 let me know if you need any help in finding it

**Comment by masif2002** [comment]
> as you have done some good work here we have some more related issues with which you can help @masif2002 let me know if you need any help in finding it

Sure, i'll take a look

**Comment by Yashsharma1911** [comment]
> > as you have done some good work here we have some more related issues with which you can help @masif2002 let me know if you need any help in finding it
> 
> Sure, i'll take a look

@masif did you find any issue to work on or do you need any help?

**Pull request merged**
